### ISSUE TITLE
Refresh innerHTML instead of navigating to /pageX

### ISSUE THREAD

**Issue by ryanipark** [467Group3A/rimjobs#37]
Found a way using express that will allow us to have 

rimjobs.store/admin.html

and when you click on vieworders it will render /vieworders and stay on /admin.html

We can do this to have only two address for /admin , /employee

Might be more clean. but there are some possible issues to it.

**Comment by Master449** [comment]
I am going to close this, while it is a great idea, the project has come too far to implement it in a timely matter.
